# Web Service
{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novahost.fullname" . }}-web
  labels:
    {{- include "novahost.labels" . | nindent 4 }}
    component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "novahost.selectorLabels" . | nindent 4 }}
    component: web
---
{{- end }}
# API Service
{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novahost.fullname" . }}-api
  labels:
    {{- include "novahost.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "novahost.selectorLabels" . | nindent 4 }}
    component: api
---
{{- end }}
# Reverse Proxy Service
{{- if .Values.reverseProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novahost.fullname" . }}-reverse-proxy
  labels:
    {{- include "novahost.labels" . | nindent 4 }}
    component: reverse-proxy
spec:
  type: {{ .Values.reverseProxy.service.type }}
  ports:
    - port: {{ .Values.reverseProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "novahost.selectorLabels" . | nindent 4 }}
    component: reverse-proxy
{{- end }}
