apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background # Finalizer: ensures all child resources are deleted before this Application is removed
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.11
    helm:
      values: |
        installCRDs: true               # CRDs (CustomResourceDefinitions): extend Kubernetes API, required by external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true # Prune: deletes resources from cluster if removed from Git
      selfHeal: true # SelfHeal: fixes drift if someone changes resources manually in cluster
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # ServerSideApply: use Kubernetes server-side apply for smarter field ownership
