apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.27.0
    helm:
      values: |
        server:
          dev:
            enabled: false
          standalone:
            enabled: true
          ha:
            enabled: false
          dataStorage:
            enabled: true
            size: 3Gi
            storageClass: do-block-storage
        injector:
          enabled: false
        ui:
          enabled: true
          serviceType: ClusterIP
        csi:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
