apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaleDb-data
  namespace: shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: do-block-storage
