apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaleDb-config
  namespace: shared
data:
  timescaleDb.conf: |
    # timescaleDb configuration
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    shared_buffers = 128MB
    effective_cache_size = 512MB

    # TimescaleDB settings
    shared_preload_libraries = 'timescaleDb'
    timescaleDb.telemetry_level = off

  init-db.sql: |
    -- Create additional databases
    CREATE DATABASE excalidraw_db;

    -- Create users for different apps
    CREATE USER excalidraw_user WITH PASSWORD 'excalidraw_pass_123';

    -- Grant permissions
    GRANT ALL PRIVILEGES ON DATABASE novahost_db TO novahost_user;
    GRANT ALL PRIVILEGES ON DATABASE excalidraw_db TO excalidraw_user;

    -- Enable TimescaleDB on novahost_db
    \c novahost_db;
    CREATE EXTENSION IF NOT EXISTS timescaleDb CASCADE;

    -- Enable TimescaleDB on excalidraw_db  
    \c excalidraw_db;
    CREATE EXTENSION IF NOT EXISTS timescaleDb CASCADE;

---
apiVersion: v1
kind: Secret
metadata:
  name: timescaleDb-secret
  namespace: shared
type: Opaque
data:
  postgres-password: cG9zdGdyZXNZb1NoYWth
  postgres-user: bm92YWhvc3RfdXNlcg==
  user-password: bm92YWhvc3RfcGFzc18xMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaleDb
  namespace: shared
  labels:
    app: timescaleDb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaleDb
  template:
    metadata:
      labels:
        app: timescaleDb
    spec:
      containers:
        - name: timescaleDb
          image: timescale/timescaleDb:latest-pg15
          ports:
            - containerPort: 5432
              name: timescaleDb
          env:
            - name: POSTGRES_DB
              value: "novahost_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescaleDb-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaleDb-secret
                  key: user-password
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaleDb-secret
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/timescaleDb/data/pgdata
          volumeMounts:
            - name: timescaleDb-data
              mountPath: /var/lib/timescaleDb/data
            - name: timescaleDb-config
              mountPath: /etc/timescaleDb/timescaleDb.conf
              subPath: timescaleDb.conf
            - name: timescaleDb-init
              mountPath: /docker-entrypoint-initdb.d/init-db.sql
              subPath: init-db.sql
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - novahost_user
                - -d
                - novahost_db
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - novahost_user
                - -d
                - novahost_db
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: timescaleDb-data
          persistentVolumeClaim:
            claimName: timescaleDb-data
        - name: timescaleDb-config
          configMap:
            name: timescaleDb-config
        - name: timescaleDb-init
          configMap:
            name: timescaleDb-config
---
apiVersion: v1
kind: Service
metadata:
  name: timescaleDb
  namespace: shared
  labels:
    app: timescaleDb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: timescaleDb
  selector:
    app: timescaleDb
