apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: shared
data:
  redis.conf: |
    # Redis configuration
    bind 0.0.0.0
    port 6379

    # Memory settings
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Persistence settings
    save 900 1
    save 300 10
    save 60 10000

    # Enable Redis Streams
    stream-node-max-bytes 4096
    stream-node-max-entries 100

    # Security
    protected-mode no

    # Performance
    tcp-keepalive 300
    timeout 0

    # Multi-database support (0-15)
    databases 6

  # Redis initialization script for multi database setup
  redis-init.sh: |
    #!/bin/sh
    echo "Setting up Redis databases for applications..."

    # NovaHost uses database 1
    redis-cli -a $REDIS_PASSWORD -n 1 CONFIG SET save "900 1 300 10 60 10000"
    redis-cli -a $REDIS_PASSWORD -n 1 SET "app:name" "novahost"

    # Excalidraw uses database 2  
    redis-cli -a $REDIS_PASSWORD -n 2 CONFIG SET save "900 1 300 10 60 10000"
    redis-cli -a $REDIS_PASSWORD -n 2 SET "app:name" "excalidraw"

    # Default database 0 for system/shared usage
    redis-cli -a $REDIS_PASSWORD -n 0 SET "app:name" "system"

    echo "Redis databases configured successfully"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: shared
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: shared
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: redis-init
          image: redis:7.2-alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          command:
            - sh
            - /scripts/redis-init.sh
          volumeMounts:
            - name: redis-config
              mountPath: /scripts
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          command:
            - redis-server
            - /etc/redis/redis.conf
            - --requirepass
            - $(REDIS_PASSWORD)
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --no-auth-warning
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - --no-auth-warning
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-config
          configMap:
            name: redis-config

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shared
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
