apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-externalsecret
  namespace: shared
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: secret/shared/redis
        property: redis-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: novahost-redis-externalsecret
  namespace: novahost
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: novahost-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/novahost/redis
        property: REDIS_URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: excalidraw-redis-externalsecret
  namespace: excalidraw
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: excalidraw-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/excalidraw/redis
        property: REDIS_URL
