apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-externalsecret
  namespace: shared
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: timescaledb-secret
    creationPolicy: Owner
  data:
    - secretKey: PATRONI_SUPERUSER_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: PATRONI_SUPERUSER_PASSWORD
    - secretKey: PATRONI_REPLICATION_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: PATRONI_REPLICATION_PASSWORD
    - secretKey: PATRONI_admin_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: PATRONI_admin_PASSWORD
    - secretKey: NOVAHOST_DB_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: NOVAHOST_DB_PASSWORD
    - secretKey: EXCALIDRAW_DB_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: EXCALIDRAW_DB_PASSWORD
