apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-externalsecret
  namespace: shared
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: timescaledb-secret
    creationPolicy: Owner
  data:
    - secretKey: PATRONI_SUPERUSER_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: PATRONI_SUPERUSER_PASSWORD
    - secretKey: PATRONI_REPLICATION_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: PATRONI_REPLICATION_PASSWORD
    - secretKey: PATRONI_admin_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: PATRONI_admin_PASSWORD
    - secretKey: NOVAHOST_DB_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: NOVAHOST_DB_PASSWORD
    - secretKey: EXCALIDRAW_DB_PASSWORD
      remoteRef:
        key: secret/shared/timescaledb
        property: EXCALIDRAW_DB_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: novahost-timescaledb-secret
  namespace: novahost
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: novahost-timescaledb-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URL
      remoteRef:
        key: secret/novahost/redis
        property: POSTGRES_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/novahost/redis
        property: REDIS_URL
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: secret/novahost/app
        property: NEXTAUTH_SECRET
    - secretKey: NEXTAUTH_URL
      remoteRef:
        key: secret/novahost/app
        property: NEXTAUTH_URL
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: secret/novahost/oauth
        property: GITHUB_CLIENT_ID
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: secret/novahost/oauth
        property: GITHUB_CLIENT_SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/novahost/oauth
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: secret/novahost/oauth
        property: GOOGLE_CLIENT_SECRET
    - secretKey: R2_ENDPOINT
      remoteRef:
        key: secret/novahost/r2
        property: R2_ENDPOINT
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: secret/novahost/r2
        property: R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/novahost/r2
        property: R2_SECRET_ACCESS_KEY
    - secretKey: R2_BUCKET_NAME
      remoteRef:
        key: secret/novahost/r2
        property: R2_BUCKET_NAME
    - secretKey: BASE_PATH
      remoteRef:
        key: secret/novahost/r2
        property: BASE_PATH
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: secret/novahost/app
        property: RESEND_API_KEY
    - secretKey: EMAIL_FROM
      remoteRef:
        key: secret/novahost/app
        property: EMAIL_FROM
