apiVersion: v1
kind: Secret
metadata:
  name: novahost-app-secret
  namespace: novahost
type: Opaque
stringData:
  NEXTAUTH_SECRET: "REPLACE_WITH_NEXTAUTH_SECRET"
  NEXTAUTH_URL: "https://novahost.ybro.tech"
  NODE_ENV: "production"
  RESEND_API_KEY: "REPLACE_WITH_RESEND_API_KEY"
  EMAIL_FROM: "REPLACE_WITH_EMAIL_FROM"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"