apiVersion: v1
kind: Secret
metadata:
  name: novahost-database-secret
  namespace: novahost
type: Opaque
stringData:
  DATABASE_URL: "postgresql://novahost:REPLACE_WITH_PASSWORD@postgresql.shared.svc.cluster.local:5432/novahost?schema=public"